version: 2.1

orbs:
  node: circleci/node@4.1
  docker: circleci/docker@1.4.0
jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: tuanlt79/react-docker
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints: 79:22:6f:1d:00:1c:ef:0b:37:c0:4d:3e:dc:57:41:16
      - run: ssh -oStrictHostKeyChecking=no tuan_lt230295@34.121.42.84 "./deploy.sh"

workflows:
  my-pipeline:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build-and-push
